# Generated by Django 3.1.6 on 2021-02-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='aadharNo',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='product',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='product',
            field=models.ManyToManyField(blank=True, to='food.Product'),
        ),
    ]
