# Generated by Django 3.1.6 on 2021-02-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadharNo',
            field=models.IntegerField(default=0),
        ),
    ]
