# Generated by Django 3.1.6 on 2021-02-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210209_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='onTheWay',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='orderImg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
