# Generated by Django 3.1.6 on 2021-02-10 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_auto_20210209_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='orderImg',
        ),
        migrations.AddField(
            model_name='shop',
            name='ShopImg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
