# Generated by Django 3.1.6 on 2021-02-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210205_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='orderFrom',
        ),
    ]
