# Generated by Django 3.1.6 on 2021-02-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210210_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.shoplocality'),
        ),
    ]
