# Generated by Django 3.1.6 on 2021-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_customerorder_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
