# Generated by Django 3.1.6 on 2021-02-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_customerprofile_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.shoplocality'),
        ),
    ]
