# Generated by Django 3.1.6 on 2021-02-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_customerorder_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='deliveryboy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.deliveryprofile'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.shoplocality'),
        ),
    ]
