# Generated by Django 3.1.6 on 2021-02-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210211_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
