# Generated by Django 3.1.6 on 2021-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20210317_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='addressinwords',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='currentOffer',
            field=models.FloatField(),
        ),
    ]
