# Generated by Django 3.1.6 on 2021-03-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20210317_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireabaseToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
            ],
        ),
    ]
