# Generated by Django 3.1.6 on 2021-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_fireabasetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
