# Generated by Django 3.1.6 on 2021-03-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_fireabasetoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='orderImg',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
