# Generated by Django 3.1.6 on 2021-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_customerorder_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='OTP',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
