# Generated by Django 3.1.6 on 2021-03-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_auto_20210322_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuanities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.product')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='quantites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.productquanities'),
        ),
    ]
