# Generated by Django 3.1.6 on 2021-03-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_auto_20210323_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='quantites',
        ),
        migrations.AddField(
            model_name='productquanities',
            name='orderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.customerorder'),
        ),
    ]
