# Generated by Django 3.1.6 on 2021-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_storeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
